//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.26 at 08:55:48 PM MSK 
//


package main.java.bmstu.iu8.analyzer.datasource.xml;

import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _XmlAlert_QNAME = new QName("", "XmlAlert");
    private final static QName _XmlMitreSource_QNAME = new QName("", "XmlMitreSource");
    private final static QName _XmlWeakness_QNAME = new QName("", "XmlWeakness");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XmlAlertType }
     * 
     */
    
    public XmlAlertType createXmlAlertType() {
        return new XmlAlertType();
    }
    
    public XmlAlertType createXmlAlertType(BigInteger id, XMLGregorianCalendar timestamp, String description, BigInteger weaknessId) {
        return new XmlAlertType(id, timestamp, description, weaknessId);
    }

    /**
     * Create an instance of {@link XmlMitreSourceType }
     * 
     */
    
    public XmlMitreSourceType createXmlMitreSourceType() {
        return new XmlMitreSourceType();
    }
    
    public XmlMitreSourceType createXmlMitreSourceType(String name, BigInteger number, String url) {
        return new XmlMitreSourceType(name, number, url);
    }

    /**
     * Create an instance of {@link XmlWeaknessType }
     * 
     */
    
    public XmlWeaknessType createXmlWeaknessType() {
        return new XmlWeaknessType();
    }

    
    public XmlWeaknessType createXmlWeaknessType(String description, String category, XmlMitreSourceType cwe, XmlMitreSourceType capec) {
        return new XmlWeaknessType(description, category, cwe, capec);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlAlertType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "XmlAlert")
    public JAXBElement<XmlAlertType> createXmlAlert(XmlAlertType value) {
        return new JAXBElement<XmlAlertType>(_XmlAlert_QNAME, XmlAlertType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlMitreSourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "XmlMitreSource")
    public JAXBElement<XmlMitreSourceType> createXmlMitreSource(XmlMitreSourceType value) {
        return new JAXBElement<XmlMitreSourceType>(_XmlMitreSource_QNAME, XmlMitreSourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XmlWeaknessType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "XmlWeakness")
    public JAXBElement<XmlWeaknessType> createXmlWeakness(XmlWeaknessType value) {
        return new JAXBElement<XmlWeaknessType>(_XmlWeakness_QNAME, XmlWeaknessType.class, null, value);
    }

}
