//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.26 at 08:55:48 PM MSK 
//


package main.java.bmstu.iu8.analyzer.datasource.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for XmlWeaknessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XmlWeaknessType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cwe" type="{}XmlMitreSourceType"/>
 *         &lt;element name="capec" type="{}XmlMitreSourceType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XmlWeaknessType", propOrder = {
    "description",
    "category",
    "cwe",
    "capec"
})
public class XmlWeaknessType {

    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String category;
    @XmlElement(required = true)
    protected XmlMitreSourceType cwe;
    @XmlElement(required = true)
    protected XmlMitreSourceType capec;
    
    public XmlWeaknessType() {};

    public XmlWeaknessType(String description, String category, XmlMitreSourceType cwe, XmlMitreSourceType capec) {
		super();
		this.description = description;
		this.category = category;
		this.cwe = cwe;
		this.capec = capec;
	}

	/**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the cwe property.
     * 
     * @return
     *     possible object is
     *     {@link XmlMitreSourceType }
     *     
     */
    public XmlMitreSourceType getCwe() {
        return cwe;
    }

    /**
     * Sets the value of the cwe property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlMitreSourceType }
     *     
     */
    public void setCwe(XmlMitreSourceType value) {
        this.cwe = value;
    }

    /**
     * Gets the value of the capec property.
     * 
     * @return
     *     possible object is
     *     {@link XmlMitreSourceType }
     *     
     */
    public XmlMitreSourceType getCapec() {
        return capec;
    }

    /**
     * Sets the value of the capec property.
     * 
     * @param value
     *     allowed object is
     *     {@link XmlMitreSourceType }
     *     
     */
    public void setCapec(XmlMitreSourceType value) {
        this.capec = value;
    }

}
